### ISSUE TITLE
run code get error

### ISSUE THREAD

**Issue by csufangyu** [stanford-iprl-lab/torchfilter#6]
I install this package as 
```
$ git clone https://github.com/stanford-iprl-lab/torchfilter.git
$ cd torchfilter
$ pip install -e .
```
but when I run 
`import torchfilter`

I get the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fangyu/robot_learning/touchvision/torchfilter/torchfilter/__init__.py", line 1, in <module>
    from . import base, data, filters, train, types, utils
  File "/home/fangyu/robot_learning/touchvision/torchfilter/torchfilter/base/__init__.py", line 4, in <module>
    from ._dynamics_model import DynamicsModel
  File "/home/fangyu/robot_learning/touchvision/torchfilter/torchfilter/base/_dynamics_model.py", line 15, in <module>
    class DynamicsModel(nn.Module, abc.ABC):
  File "/home/fangyu/robot_learning/touchvision/torchfilter/torchfilter/base/_dynamics_model.py", line 35, in DynamicsModel
    ) -> Tuple[types.StatesTorch, types.ScaleTrilTorch]:
  File "/home/fangyu/.conda/envs/robosuite/lib/python3.7/site-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/home/fangyu/.conda/envs/robosuite/lib/python3.7/site-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/home/fangyu/.conda/envs/robosuite/lib/python3.7/site-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/home/fangyu/.conda/envs/robosuite/lib/python3.7/site-packages/overrides/signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/home/fangyu/.conda/envs/robosuite/lib/python3.7/site-packages/overrides/signature.py", line 288, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: DynamicsModel.forward: return type `typing.Tuple[torch.Tensor, torch.Tensor]` is not a `<class 'NoneType'>`.
```
could you hlep me?Thanks

**Comment by csufangyu** [comment]
Thanks,I have fixed.I use the 
`pip install overrides==2.0`
